version: 2
jobs:
  build:
    docker:
      - image: circleci/node:jessie-browsers
    working_directory: ~/app
    steps:
      - run:
          name: Check Chrome version
          command: google-chrome --version
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --ignore-engines --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache
      - run: yarn lint
      - run: yarn test
      - store_artifacts:
          path: ~/app/build
